/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.configurador.view;

import com.mycompany.configurador.model.Peca;

/**
 *
 * @author diego
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        carregarProcessadores();
        carregarMemorias();
        carregarPlacasVideo();
        carregarArmazenamentos(); 
        carregarPerifericos();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaResumo = new javax.swing.JList<>();
        lblTotal = new javax.swing.JLabel();
        barraEnergia = new javax.swing.JProgressBar();
        barraDesempenho = new javax.swing.JProgressBar();
        chkCoolerExtra = new javax.swing.JCheckBox();
        chkRgb = new javax.swing.JCheckBox();
        chkGarantiaEstendida = new javax.swing.JCheckBox();
        btnExportar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panProcessador = new javax.swing.JPanel();
        cmbProcessador = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProcessador = new javax.swing.JTable();
        panPlacaDeVideo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPlacaVideo = new javax.swing.JTable();
        cmbPlacaVideo = new javax.swing.JComboBox<>();
        panMemoriaRam = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMemoria = new javax.swing.JTable();
        cmbMemoria = new javax.swing.JComboBox<>();
        panArmazenamento = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblArmazenamento = new javax.swing.JTable();
        cmbArmazenamento = new javax.swing.JComboBox<>();
        panPerifericos = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPerifericos = new javax.swing.JTable();
        cmbPerifericos = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemExportar = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sua Build"));

        listaResumo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaResumo);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setText("TOTAL: R$ 0,00");

        barraEnergia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraEnergia.setMaximum(750);
        barraEnergia.setString("Consumo: 0W / 750W");
        barraEnergia.setStringPainted(true);

        barraDesempenho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraDesempenho.setString("Score de Desempenho");
        barraDesempenho.setStringPainted(true);

        chkCoolerExtra.setText("Cooler extra");
        chkCoolerExtra.addActionListener(this::chkCoolerExtraActionPerformed);

        chkRgb.setText("RGB");
        chkRgb.addActionListener(this::chkRgbActionPerformed);

        chkGarantiaEstendida.setText("Garantia estendida");
        chkGarantiaEstendida.addActionListener(this::chkGarantiaEstendidaActionPerformed);

        btnExportar.setBackground(new java.awt.Color(51, 153, 255));
        btnExportar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar / Finalizar");
        btnExportar.addActionListener(this::btnExportarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barraDesempenho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barraEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(chkCoolerExtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkRgb)
                        .addGap(18, 18, 18)
                        .addComponent(chkGarantiaEstendida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(btnExportar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraDesempenho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCoolerExtra)
                    .addComponent(chkRgb)
                    .addComponent(chkGarantiaEstendida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbProcessador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ryzen 5 8600G", "I3-10100F", " " }));
        cmbProcessador.addActionListener(this::cmbProcessadorActionPerformed);

        tblProcessador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Especificação", "Detalhe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProcessador);

        javax.swing.GroupLayout panProcessadorLayout = new javax.swing.GroupLayout(panProcessador);
        panProcessador.setLayout(panProcessadorLayout);
        panProcessadorLayout.setHorizontalGroup(
            panProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProcessadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(cmbProcessador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panProcessadorLayout.setVerticalGroup(
            panProcessadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProcessadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Processador", panProcessador);

        tblPlacaVideo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Especificação", "Detalhe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblPlacaVideo);

        cmbPlacaVideo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ryzen 5 8600G", "I3-10100F", " " }));
        cmbPlacaVideo.addActionListener(this::cmbPlacaVideoActionPerformed);

        javax.swing.GroupLayout panPlacaDeVideoLayout = new javax.swing.GroupLayout(panPlacaDeVideo);
        panPlacaDeVideo.setLayout(panPlacaDeVideoLayout);
        panPlacaDeVideoLayout.setHorizontalGroup(
            panPlacaDeVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPlacaDeVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPlacaDeVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(cmbPlacaVideo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panPlacaDeVideoLayout.setVerticalGroup(
            panPlacaDeVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPlacaDeVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbPlacaVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Placa de vídeo", panPlacaDeVideo);

        tblMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Especificação", "Detalhe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblMemoria);

        cmbMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ryzen 5 8600G", "I3-10100F", " " }));
        cmbMemoria.addActionListener(this::cmbMemoriaActionPerformed);

        javax.swing.GroupLayout panMemoriaRamLayout = new javax.swing.GroupLayout(panMemoriaRam);
        panMemoriaRam.setLayout(panMemoriaRamLayout);
        panMemoriaRamLayout.setHorizontalGroup(
            panMemoriaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMemoriaRamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMemoriaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMemoria, 0, 537, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)))
        );
        panMemoriaRamLayout.setVerticalGroup(
            panMemoriaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMemoriaRamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Memória RAM", panMemoriaRam);

        tblArmazenamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Especificação", "Detalhe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblArmazenamento);

        cmbArmazenamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ryzen 5 8600G", "I3-10100F", " " }));
        cmbArmazenamento.addActionListener(this::cmbArmazenamentoActionPerformed);

        javax.swing.GroupLayout panArmazenamentoLayout = new javax.swing.GroupLayout(panArmazenamento);
        panArmazenamento.setLayout(panArmazenamentoLayout);
        panArmazenamentoLayout.setHorizontalGroup(
            panArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panArmazenamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(cmbArmazenamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panArmazenamentoLayout.setVerticalGroup(
            panArmazenamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panArmazenamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbArmazenamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Armazenamento", panArmazenamento);

        tblPerifericos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Especificação", "Detalhe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblPerifericos);

        cmbPerifericos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Ryzen 5 8600G", "I3-10100F", " " }));
        cmbPerifericos.addActionListener(this::cmbPerifericosActionPerformed);

        javax.swing.GroupLayout panPerifericosLayout = new javax.swing.GroupLayout(panPerifericos);
        panPerifericos.setLayout(panPerifericosLayout);
        panPerifericosLayout.setHorizontalGroup(
            panPerifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPerifericosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPerifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(cmbPerifericos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panPerifericosLayout.setVerticalGroup(
            panPerifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPerifericosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbPerifericos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Periféricos", panPerifericos);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Arquivo");

        menuItemExportar.setText("Exportar Build");
        menuItemExportar.addActionListener(this::menuItemExportarActionPerformed);
        jMenu1.add(menuItemExportar);

        menuSair.setText("Sair");
        menuSair.addActionListener(this::menuSairActionPerformed);
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        menuSobre.setText("Equipe de Desenvolvimento");
        menuSobre.addActionListener(this::menuSobreActionPerformed);
        jMenu2.add(menuSobre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        //fecha o sistema
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        
       //Mensagem de desenvolvimento 
       javax.swing.JOptionPane.showMessageDialog(this, 
    "Configurador de PC Gamer\n\n" +
    "Desenvolvido por: Diego Oliveira Ricardo\n" +
    "Disciplina: Programação de Computadores II", 
    "Sobre o Sistema", 
    javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuSobreActionPerformed

    private void cmbProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProcessadorActionPerformed
        
        if (cmbProcessador.getSelectedItem() instanceof Peca) {
            
            Peca pecaSelecionada = (Peca) cmbProcessador.getSelectedItem();
            
            if (pecaSelecionada != null && pecaSelecionada.getPreco() > 0) {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblProcessador.getModel();
                modelo.setRowCount(0);
                modelo.addRow(new Object[]{"Especificação", pecaSelecionada.getDetalhe1()});
                modelo.addRow(new Object[]{"Detalhe", pecaSelecionada.getDetalhe2()});
                modelo.addRow(new Object[]{"TDP (Consumo)", pecaSelecionada.getTdp() + "W"});
                modelo.addRow(new Object[]{"Preço", String.format("R$ %.2f", pecaSelecionada.getPreco())});
            }
        }
        atualizarResumo();                                          
    }//GEN-LAST:event_cmbProcessadorActionPerformed

    private void cmbMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMemoriaActionPerformed
        // Verifica se o que está selecionado é realmente uma Peca, e não o texto "Item 1"
        if (cmbMemoria.getSelectedItem() instanceof Peca) {
            
            Peca pecaSelecionada = (Peca) cmbMemoria.getSelectedItem();
            
            if (pecaSelecionada != null && pecaSelecionada.getPreco() > 0) {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblMemoria.getModel();
                modelo.setRowCount(0);
                modelo.addRow(new Object[]{"Especificação", pecaSelecionada.getDetalhe1()});
                modelo.addRow(new Object[]{"Detalhe", pecaSelecionada.getDetalhe2()});
                modelo.addRow(new Object[]{"TDP (Consumo)", pecaSelecionada.getTdp() + "W"});
                modelo.addRow(new Object[]{"Preço", String.format("R$ %.2f", pecaSelecionada.getPreco())});
            }
        }
        atualizarResumo();
    }//GEN-LAST:event_cmbMemoriaActionPerformed

    private void cmbPlacaVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlacaVideoActionPerformed
        if (cmbPlacaVideo.getSelectedItem() instanceof Peca) {
            Peca pecaSelecionada = (Peca) cmbPlacaVideo.getSelectedItem();
            
            if (pecaSelecionada != null && pecaSelecionada.getPreco() > 0) {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPlacaVideo.getModel();
                modelo.setRowCount(0);
                modelo.addRow(new Object[]{"Especificação", pecaSelecionada.getDetalhe1()});
                modelo.addRow(new Object[]{"Detalhe", pecaSelecionada.getDetalhe2()});
                modelo.addRow(new Object[]{"TDP (Consumo)", pecaSelecionada.getTdp() + "W"});
                modelo.addRow(new Object[]{"Preço", String.format("R$ %.2f", pecaSelecionada.getPreco())});
            }
        }
        atualizarResumo(); 
    }//GEN-LAST:event_cmbPlacaVideoActionPerformed

    private void chkCoolerExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCoolerExtraActionPerformed
        atualizarResumo();
    }//GEN-LAST:event_chkCoolerExtraActionPerformed

    private void chkRgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRgbActionPerformed
        atualizarResumo();
    }//GEN-LAST:event_chkRgbActionPerformed

    private void chkGarantiaEstendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGarantiaEstendidaActionPerformed
        atualizarResumo();
    }//GEN-LAST:event_chkGarantiaEstendidaActionPerformed

    private void cmbArmazenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArmazenamentoActionPerformed
        if (cmbArmazenamento.getSelectedItem() instanceof Peca) {
            Peca peca = (Peca) cmbArmazenamento.getSelectedItem();
            if (peca != null && peca.getPreco() > 0) {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblArmazenamento.getModel();
                modelo.setRowCount(0);
                modelo.addRow(new Object[]{"Especificação", peca.getDetalhe1()});
                modelo.addRow(new Object[]{"Detalhe", peca.getDetalhe2()});
                modelo.addRow(new Object[]{"TDP (Consumo)", peca.getTdp() + "W"});
                modelo.addRow(new Object[]{"Preço", String.format("R$ %.2f", peca.getPreco())});
            }
        }
        atualizarResumo();
    }//GEN-LAST:event_cmbArmazenamentoActionPerformed

    private void cmbPerifericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPerifericosActionPerformed
        if (cmbPerifericos.getSelectedItem() instanceof Peca) {
            Peca peca = (Peca) cmbPerifericos.getSelectedItem();
            if (peca != null && peca.getPreco() > 0) {
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPerifericos.getModel();
                modelo.setRowCount(0);
                modelo.addRow(new Object[]{"Especificação", peca.getDetalhe1()});
                modelo.addRow(new Object[]{"Detalhe", peca.getDetalhe2()});
                modelo.addRow(new Object[]{"TDP (Consumo)", peca.getTdp() + "W"});
                modelo.addRow(new Object[]{"Preço", String.format("R$ %.2f", peca.getPreco())});
            }
        }
        atualizarResumo();
    }//GEN-LAST:event_cmbPerifericosActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Salvar Resumo da Build");
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            
            try (java.io.FileWriter fw = new java.io.FileWriter(fileToSave + ".txt")) {
                fw.write("=== ORÇAMENTO - PC GAMER ===\n\n");
                
                // Puxa os itens da lista lateral
                javax.swing.ListModel<String> model = listaResumo.getModel();
                for (int i = 0; i < model.getSize(); i++) {
                    fw.write(model.getElementAt(i) + "\n");
                }
                
                fw.write("\n" + lblTotal.getText() + "\n");
                fw.write("Status de Energia: " + barraEnergia.getString() + "\n");
                
                javax.swing.JOptionPane.showMessageDialog(this, "Orçamento exportado com sucesso!\nSalvo em: " + fileToSave.getAbsolutePath(), "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar o arquivo: " + ex.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void menuItemExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExportarActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Salvar Resumo da Build");
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            
            try (java.io.FileWriter fw = new java.io.FileWriter(fileToSave + ".txt")) {
                fw.write("=== ORÇAMENTO - PC GAMER ===\n\n");
                
                // Puxa os itens da lista lateral
                javax.swing.ListModel<String> model = listaResumo.getModel();
                for (int i = 0; i < model.getSize(); i++) {
                    fw.write(model.getElementAt(i) + "\n");
                }
                
                fw.write("\n" + lblTotal.getText() + "\n");
                fw.write("Status de Energia: " + barraEnergia.getString() + "\n");
                
                javax.swing.JOptionPane.showMessageDialog(this, "Orçamento exportado com sucesso!\nSalvo em: " + fileToSave.getAbsolutePath(), "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar o arquivo: " + ex.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_menuItemExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraDesempenho;
    private javax.swing.JProgressBar barraEnergia;
    private javax.swing.JButton btnExportar;
    private javax.swing.JCheckBox chkCoolerExtra;
    private javax.swing.JCheckBox chkGarantiaEstendida;
    private javax.swing.JCheckBox chkRgb;
    private javax.swing.JComboBox<Object> cmbArmazenamento;
    private javax.swing.JComboBox<Object> cmbMemoria;
    private javax.swing.JComboBox<Object> cmbPerifericos;
    private javax.swing.JComboBox<Object> cmbPlacaVideo;
    private javax.swing.JComboBox<Object> cmbProcessador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> listaResumo;
    private javax.swing.JMenuItem menuItemExportar;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JPanel panArmazenamento;
    private javax.swing.JPanel panMemoriaRam;
    private javax.swing.JPanel panPerifericos;
    private javax.swing.JPanel panPlacaDeVideo;
    private javax.swing.JPanel panProcessador;
    private javax.swing.JTable tblArmazenamento;
    private javax.swing.JTable tblMemoria;
    private javax.swing.JTable tblPerifericos;
    private javax.swing.JTable tblPlacaVideo;
    private javax.swing.JTable tblProcessador;
    // End of variables declaration//GEN-END:variables

    //Define os itens da comboBox Processadores
    private void carregarProcessadores() {
        cmbProcessador.removeAllItems();
        cmbProcessador.addItem(new Peca("Selecione...", 0, 0, 0, "-", "-"));
        
        cmbProcessador.addItem(new Peca("Ryzen 5 8600G", 1350.00, 65, 85, "Socket AM5", "Vídeo Integrado Radeon 760M"));
        cmbProcessador.addItem(new Peca("Core i3-10100F", 450.00, 65, 40, "Socket LGA1200", "Sem vídeo integrado"));
        cmbProcessador.addItem(new Peca("Ryzen 7 5700X3D", 1550.00, 105, 95, "Socket AM4", "Cache L3 Gigante (Jogos)"));
        cmbProcessador.addItem(new Peca("Core i5-13400F", 1250.00, 65, 88, "Socket LGA1700", "10 Núcleos / 16 Threads"));
    }

    //Define os itens da comboBox Placas de video
    private void carregarPlacasVideo() {
        cmbPlacaVideo.removeAllItems();
        cmbPlacaVideo.addItem(new Peca("Selecione...", 0, 0, 0, "-", "-"));
        
        cmbPlacaVideo.addItem(new Peca("RTX 4060 8GB", 1850.00, 115, 95, "GDDR6", "NVIDIA DLSS 3 e Ray Tracing"));
        cmbPlacaVideo.addItem(new Peca("RX 7600 8GB", 1700.00, 130, 90, "GDDR6", "AMD RDNA 3"));
        cmbPlacaVideo.addItem(new Peca("RTX 3060 12GB", 1550.00, 170, 85, "GDDR6", "Ideal para edição e 1080p"));
        cmbPlacaVideo.addItem(new Peca("RX 6600 8GB", 1350.00, 132, 75, "GDDR6", "Excelente custo-benefício"));
    }
    
    //Define os itens da comboBox Memorias
    private void carregarMemorias() {
        cmbMemoria.removeAllItems();
        cmbMemoria.addItem(new Peca("Selecione...", 0, 0, 0, "-", "-"));
        
        cmbMemoria.addItem(new Peca("2x 8GB DDR5 5600MHz", 450.00, 10, 80, "Dual Channel", "Alta Frequência DDR5"));
        cmbMemoria.addItem(new Peca("2x 16GB DDR5 6000MHz", 850.00, 12, 95, "Dual Channel", "Máximo Desempenho"));
        cmbMemoria.addItem(new Peca("1x 16GB DDR4 3200MHz", 220.00, 5, 45, "Single Channel", "Padrão Custo Benefício"));
        cmbMemoria.addItem(new Peca("2x 8GB DDR4 3200MHz", 260.00, 8, 60, "Dual Channel", "Ideal para AM4/LGA1200"));
    }
    
    //Define os itens da comboBox Armazenamentos
    private void carregarArmazenamentos() {
        cmbArmazenamento.removeAllItems();
        cmbArmazenamento.addItem(new Peca("Selecione...", 0, 0, 0, "-", "-"));
        
        cmbArmazenamento.addItem(new Peca("SSD 1TB NVMe M.2 PCIe 4.0", 550.00, 5, 80, "Leitura 7000MB/s", "Geração 4 ultra rápida"));
        cmbArmazenamento.addItem(new Peca("SSD 500GB NVMe M.2", 300.00, 5, 50, "Leitura 3500MB/s", "PCIe 3.0"));
        cmbArmazenamento.addItem(new Peca("HD 2TB SATA 3", 350.00, 10, 20, "7200 RPM", "Armazenamento em massa"));
        
        cmbArmazenamento.addItem(new Peca("COMBO: SSD 1TB NVMe + HD 2TB", 900.00, 15, 85, "Velocidade e Espaço", "Sistema no SSD, Jogos no HD"));
    }

    //Define os itens da comboBox Perifericos
    private void carregarPerifericos() {
        cmbPerifericos.removeAllItems();
        cmbPerifericos.addItem(new Peca("Selecione...", 0, 0, 0, "-", "-"));
        
        cmbPerifericos.addItem(new Peca("Monitor 24\" 144Hz IPS", 850.00, 30, 80, "Painel IPS", "1ms de tempo de resposta"));
        cmbPerifericos.addItem(new Peca("Mouse Gamer Superlight", 450.00, 2, 90, "Sem fio", "Sensor de alta precisão"));
        cmbPerifericos.addItem(new Peca("Teclado Mecânico TKL", 300.00, 5, 70, "Switch Red", "Formato compacto sem numérico"));
        
        cmbPerifericos.addItem(new Peca("KIT BÁSICO: Teclado Mecânico + Mouse", 750.00, 7, 75, "RGB Sincronizado", "Kit Custo-Benefício"));
        cmbPerifericos.addItem(new Peca("KIT COMPLETO: Monitor + Teclado + Mouse + Headset", 1850.00, 42, 95, "Setup Completo", "Pronto para jogar"));
    }
    
    /**
     * Método central de inteligência do sistema.
     * Atualiza o preço total, a barra de energia, o score e a lista lateral.
     */
    private void atualizarResumo() {
        double totalPreco = 0.0;
        int totalTdp = 0;
        int totalScore = 0;
        
        javax.swing.DefaultListModel<String> modeloLista = new javax.swing.DefaultListModel<>();

        // Verifica o Processador
        if (cmbProcessador.getSelectedItem() instanceof Peca) {
            Peca proc = (Peca) cmbProcessador.getSelectedItem();
            if (proc.getPreco() > 0) {
                totalPreco += proc.getPreco();
                totalTdp += proc.getTdp();
                totalScore += proc.getScore();
                modeloLista.addElement("CPU: " + proc.getNome());
            }
        }

        // Verifica a Placa de Vídeo
        if (cmbPlacaVideo.getSelectedItem() instanceof Peca) {
            Peca video = (Peca) cmbPlacaVideo.getSelectedItem();
            if (video.getPreco() > 0) {
                totalPreco += video.getPreco();
                totalTdp += video.getTdp();
                totalScore += video.getScore();
                modeloLista.addElement("Vídeo/Placa: " + video.getNome());
            }
        }

        // Verifica a Memória RAM
        if (cmbMemoria.getSelectedItem() instanceof Peca) {
            Peca ram = (Peca) cmbMemoria.getSelectedItem();
            if (ram.getPreco() > 0) {
                totalPreco += ram.getPreco();
                totalTdp += ram.getTdp();
                totalScore += ram.getScore();
                modeloLista.addElement("RAM: " + ram.getNome());
            }
        }

        // Verifica o Armazenamento
        if (cmbArmazenamento.getSelectedItem() instanceof Peca) {
            Peca arm = (Peca) cmbArmazenamento.getSelectedItem();
            if (arm.getPreco() > 0) {
                totalPreco += arm.getPreco();
                totalTdp += arm.getTdp();
                totalScore += arm.getScore();
                modeloLista.addElement("Disco: " + arm.getNome());
            }
        }

        // Verifica os Periféricos
        if (cmbPerifericos.getSelectedItem() instanceof Peca) {
            Peca per = (Peca) cmbPerifericos.getSelectedItem();
            if (per.getPreco() > 0) {
                totalPreco += per.getPreco();
                totalTdp += per.getTdp();
                totalScore += per.getScore();
                modeloLista.addElement("Periférico: " + per.getNome());
            }
        }
        // Verifica os Opcionais
        if (chkCoolerExtra.isSelected()) { totalPreco += 150.0; modeloLista.addElement("+ Cooler Extra"); }
        if (chkRgb.isSelected()) { totalPreco += 100.0; modeloLista.addElement("+ Iluminação RGB"); }
        if (chkGarantiaEstendida.isSelected()) { totalPreco += 250.0; modeloLista.addElement("+ Garantia Estendida"); }

        // Atualiza a Interface Lateral
        listaResumo.setModel(modeloLista);
        lblTotal.setText(String.format("TOTAL: R$ %.2f", totalPreco));
        
        barraEnergia.setValue(totalTdp);
        barraEnergia.setString("Consumo: " + totalTdp + "W / 750W");
        barraDesempenho.setValue(totalScore);
    }
}

